[package]
name = "minigrep"
version = "0.1.0"
edition = "2022"
authors = ["David J Meyer"]
description = "A grep utility called from JS using Rust speed"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
